
package Vistas;

public class Vistas extends javax.swing.JFrame {

    public Vistas() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        JDPEscritorio = new javax.swing.JDesktopPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        JMAlumno = new javax.swing.JMenu();
        JMIFormularioAlumno = new javax.swing.JMenuItem();
        JMMateria = new javax.swing.JMenu();
        JMIFormularioMateria = new javax.swing.JMenuItem();
        JMAdministracion = new javax.swing.JMenu();
        JMIInscripciones = new javax.swing.JMenuItem();
        JMINotas = new javax.swing.JMenuItem();
        JMConsultas = new javax.swing.JMenu();
        JMIAlumnosPorMateria = new javax.swing.JMenuItem();
        JMSalir = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout JDPEscritorioLayout = new javax.swing.GroupLayout(JDPEscritorio);
        JDPEscritorio.setLayout(JDPEscritorioLayout);
        JDPEscritorioLayout.setHorizontalGroup(
            JDPEscritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 648, Short.MAX_VALUE)
        );
        JDPEscritorioLayout.setVerticalGroup(
            JDPEscritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 370, Short.MAX_VALUE)
        );

        JMAlumno.setText("Alumno");

        JMIFormularioAlumno.setText("Formulario de Alumno");
        JMAlumno.add(JMIFormularioAlumno);

        jMenuBar1.add(JMAlumno);

        JMMateria.setText("Materia");

        JMIFormularioMateria.setText("Formulario de Materia");
        JMMateria.add(JMIFormularioMateria);

        jMenuBar1.add(JMMateria);

        JMAdministracion.setText("Administración");

        JMIInscripciones.setText("Manejo de Inscripciones");
        JMAdministracion.add(JMIInscripciones);

        JMINotas.setText("Manipulación de notas");
        JMAdministracion.add(JMINotas);

        jMenuBar1.add(JMAdministracion);

        JMConsultas.setText("Consultas");

        JMIAlumnosPorMateria.setText("Alumnos por Materia");
        JMConsultas.add(JMIAlumnosPorMateria);

        jMenuBar1.add(JMConsultas);

        JMSalir.setText("Salir");
        jMenuBar1.add(JMSalir);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(JDPEscritorio)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(JDPEscritorio)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Vistas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Vistas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Vistas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Vistas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Vistas().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane JDPEscritorio;
    private javax.swing.JMenu JMAdministracion;
    private javax.swing.JMenu JMAlumno;
    private javax.swing.JMenu JMConsultas;
    private javax.swing.JMenuItem JMIAlumnosPorMateria;
    private javax.swing.JMenuItem JMIFormularioAlumno;
    private javax.swing.JMenuItem JMIFormularioMateria;
    private javax.swing.JMenuItem JMIInscripciones;
    private javax.swing.JMenuItem JMINotas;
    private javax.swing.JMenu JMMateria;
    private javax.swing.JMenu JMSalir;
    private javax.swing.JMenuBar jMenuBar1;
    // End of variables declaration//GEN-END:variables


}
